services:
  postgres:
    image: postgres:17.5
    container_name: postgres
    environment:
      POSTGRES_USER: wallet
      POSTGRES_PASSWORD: wallet
      POSTGRES_DB: wallet
    ports:
      - 5432:5432
    volumes:
      - ./volume/wallet/postgres:/var/lib/postgresql/data